#!/bin/bash
### BEGIN INIT INFO
# Provides:       avf-set-root-password
# Required-Start: avf-configure-networking
# Required-Stop:  
# Should-Start:   
# Should-Stop:    
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    sets the root password from the MDS data on first boot
### END INIT INFO
# chkconfig: 123 99 99

if [ -f /var/local/lib/avf/has-run/set-root-password ]; then
	exit 0
fi

export RUNNING_FROM_SYSVINIT=yes

case "$1" in
	start)
		exec /usr/local/share/avf/bin/set-root-password
		;;
	*)
		# Do nothing.
		;;
esac

:
