#!/bin/bash
### BEGIN INIT INFO
# Provides:       avf-configure-networking
# X-Start-Before: $network
# Required-Start: $local_fs
# Required-Stop:  
# Should-Start:   
# Should-Stop:    
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Configure any network interface that isn't already
### END INIT INFO
# chkconfig: 123 98 98

if [ -f /var/local/lib/avf/has-run/configure-networking ]; then
	exit 0
fi

export RUNNING_FROM_SYSVINIT=yes

case "$1" in
	start)
		/usr/local/share/avf/bin/connect-to-mds || exit 1
		exec /usr/local/share/avf/bin/configure-networking
		;;
	*)
		# Do nothing.
		;;
esac

:
