#!/bin/sh
### BEGIN INIT INFO
# Provides:       generate-ssh-hostkeys
# Required-Start: $local_fs
# Required-Stop:  
# Should-Start:   
# Should-Stop:    
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Generate ssh host keys if they do not exist
### END INIT INFO

if [ -f /etc/ssh/ssh_host_rsa_key -o -f /etc/ssh/ssh_host_dsa_key ]; then
	exit 0
fi

case "$1" in
	start)
		exec ssh-keygen -A
		;;
	*)
		# Do nothing.
		;;
esac

:
